
services:
  otp:
    ports:
      - "8080:8080"
  opensearch:
    ports:
      - "9200:9200"
      - "9600:9600"
  opensearch-dashboards:
    ports:
      - "5601:5601"
  backend:
    ports:
      - "8000:8000"
  frontend:
    environment:
      # tells which compse we are running to select the correct port
      - VITE_RUNNING_COMP=DEV
    ports:
      - "5173:80"

volumes:
  kira-opensearch-data:
  bc-data: