
services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_proxy
    restart: always

  frontend:
    environment:
      # tells which compse we are running to select the correct port
      - VITE_RUNNING_COMP=PROD
    networks:
      - default
      - nginx_proxy

  backend:
    networks:
      - default
      - nginx_proxy
  
  opensearch-dashboards:
    ports:
      - "5601:5601"

networks:
  nginx_proxy:
    external: true

volumes:
  opensearch-data:
  bc-data: