version: "3.9"

services:
  otp:
    image: opentripplanner/opentripplanner:latest
    container_name: otp
    ports:
      - "8080:8080"
    working_dir: /var/opentripplanner
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx20g"
    volumes:
      - ./otp-data:/var/opentripplanner
    command:
      - "--load"
      - "--serve"

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=KiraTestHype40!
    ports:
      - "9200:9200"
    volumes:
      - os-data:/usr/share/opensearch/data
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    restart: unless-stopped

  trip-planner:
    build: ./trip-planner
    container_name: trip-planner
    environment:
      - OTP_URL=http://otp:8080/otp/routers/default/index/graphql
      - OTP_TIMEOUT_SEC=30
      - OPENSEARCH_ENABLED=true
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_INDEX=travel-plans
      
    ports:
      - "8001:8001"
    depends_on:
      - otp
      - opensearch
    restart: unless-stopped
    
    
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      - TRIP_PLANNER_URL=http://trip-planner:8001
      - GATEWAY_TIMEOUT_SEC=30
      - BAYERNCLOUD_API_KEY=YOUR_KEY
      - BAYERNCLOUD_API_BASE_URL=YOUR_BASE_URL
      - BAYERNCLOUD_DATA_DIR=/data/bayerncloud
    volumes:
      - bc-data:/data/bayerncloud
    ports:
      - "8000:8000"
    depends_on:
      - trip-planner
    restart: unless-stopped

volumes:
  os-data:
  bc-data:
